//
// This is generated code.
// Please do not edit this file, rather edit the correct XML file.
//            File: include/MDSChainSubscribeModel.cpp
//  Generated From: src\codegen\src\MDSChainSubscribeModel.xml
//    Generated on: Thu Apr 23 15:51:21 BST 2015
// Generating User: v594079
// $Id$
//

namespace MdsOmNs {

// Convert a MDSChainSubscribeModel to text and vice versa.
// The subscribe model for incoming chains. This model determines how the links are examined to determine which fields to process.
const char* MDSDataChain::Get_MDSChainSubscribeModel_Text(MDSChainSubscribeModel n) {
	switch (n) {


    /**
     * Not yet determined.
     */
		case MDS_CHAIN_SUBSCRIBE_MODEL_UNKNOWN: return "MDS_CHAIN_SUBSCRIBE_MODEL_UNKNOWN"; break;

    /**
     * Original chain code.
     */
		case MDS_CHAIN_SUBSCRIBE_MODEL_V1: return "MDS_CHAIN_SUBSCRIBE_MODEL_V1"; break;

    /**
     * Kobra model.
     */
		case MDS_CHAIN_SUBSCRIBE_MODEL_KOBRA: return "MDS_CHAIN_SUBSCRIBE_MODEL_KOBRA"; break;

    /**
     * SFC model.
     */
		case MDS_CHAIN_SUBSCRIBE_MODEL_SFC: return "MDS_CHAIN_SUBSCRIBE_MODEL_SFC"; break;
	}
	return "Not Recognized???";
}

}